### ISSUE TITLE
Should we disable `react/jsx-filename-extension` rule?

### ISSUE THREAD

**Issue by ctumolosus** [flowcommerce/eslint-config-flowio#6]
As of React 0.12, [it is recommended](https://github.com/facebook/react/issues/832) to use the `.jsx` file extension rather than the pragma in `.js` files - Babel has just been good at making that transparent for us.

**Comment by ctumolosus** [comment]
@chrhicks what are your thoughts?

**Comment by chrhicks** [comment]
I wouldn't call that a recommendation :)

We can decide to use .jsx independently of that though if it simplifies
things for us!
